{% set name = "LHCbDIRAC" %}
{% set version = "9.4.14" %}
{% set major, minor, patch = version.split(".") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/lhcb-dirac/{{ name }}/-/archive/v{{ major }}r{{ minor }}p{{ patch }}/LHCbDIRAC-v{{ major }}r{{ minor }}p{{ patch }}.tar.gz
  sha256: e36f207e1a9ffc820c01868420a06177f604c8ec87ed073285d01eec605b7e63

build:
  noarch: python
  number: 0
  script:
    - cp ${RECIPE_DIR}/setup.py .
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - mkdir -p ${CONDA_PREFIX}/scripts
    - find LHCbDIRAC -wholename '*/scripts/*.py' -exec bash -xc 'FN={} && NEW_FN=${CONDA_PREFIX}/scripts/$(basename ${FN} .py) && echo cp ${FN} ${NEW_FN} && chmod +x ${NEW_FN}' \;

requirements:
  host:
    - python =2.7
    - pip
  run:
    - python =2.7
    - dirac-grid =6.22
    - lhcbdirac-config
    - voms
    - python-gfal2
    - lbplatformutils >=4.2.3
    - lbenv >=1.1.1

test:
  imports:
    - LHCbDIRAC

about:
  home: https://lhcb-dirac.readthedocs.io/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'LHCbDIRAC is the Extension to DIRAC for the LHCb Experiment'
  description: |
    DIRAC forms a layer between a particular community and various compute
    resources to allow optimized, transparent and reliable usage. LHCbDIRAC
    specializes DIRAC for LHCb.
  doc_url: https://lhcb-dirac.readthedocs.io/
  dev_url: https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC

extra:
  recipe-maintainers:
    - chrisburr
