travis:
  secure:
    BINSTAR_TOKEN: bX8kYieuREPFRfVb9JsY9J5xxNUSqKKLlJjHH/ZkRa8KisDmMVXlvWlrpwNnxuR8IWiVw05Ha3aeocD285WST7LB247ttO1IjQd3d73MtQ8lPUr2OMQFSUlq0kEaHq0chl4FlrsVx4yGbrAaSFub+AfyT1v9GlOubUNJ75sDwuCkYURWuUhyg0A8OkCEBOxGqA6Yw0yuo0w1Ir7h3FxWsY1HNzl82gVzvgmyaSfcU6OtS3NrQ6UzUtU4VnDxTfvkEJyo2SOgNChqnptoVhDXhNCipFidRjTVkXGaxDjy1nn75nwDII6Kq/GiI5LPd1TXv/wYdamEa9hh3vtHSlbnsKdu/CSIqh4ucoYWgmG9GDVGX3TzIj9FKTjAmimBTc+6EGecQgoN/6rR+5f0koYbnsGCgDuggiG10hcBwFLZUEZCQVURA3wPX3wejHYWs+SIQNU7jzafpCeNdg4COf2aBXqKd0GrDktqnw6P6SHClWPlpxqCgFiNLdM1CCBokGo5OzjhlO1mNmkdoaHYtyO34X3ewvxG0RyOEfxESldUWeiP84FBR2IV9i7/7geF54wjHFDZheDYlWEcLhKQ1zmCYviBGzRkhyCG5AjQt/Q1ZI9yy31gZNX0Cof+7hU+lNnLIDcd0rWJviACn4wMdt12VTMqxTieI/V/C55h/F+GAww=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
